### ISSUE TITLE
Didn't Work

### ISSUE THREAD

**Issue by MkfsSion** [Neo-Oli/chrooted-termux#1]

**Comment by MkfsSion** [comment]
When i run 'start.sh',it shows some errors. The error was "proot error: '/data/data/com.termux/files/usr/bin/env' not found (root = /data/data/com.termux/files/home/chrooted-termux/termux-fs, cwd = /data/data/com.termux/files/home, $PATH=(null))
fatal error: see `proot --help`."

**Comment by Neo-Oli** [comment]
It looks like your installation somehow failed. Can you delete the `termux-fs` folder and run the `chrooted-termux` script again and post it's output? There might be errors that would explain why it dîdn't install correctly.

From looking over the script, I guess an issue could arise when using the default wget. It's from busybox and doesn't work with https. Can you try installing the real wget `packages install wget`
