### ISSUE TITLE
proot error

### ISSUE THREAD

**Issue by Ublimjo** [Neo-Oli/chrooted-termux#3]
proot info: vpid 1: terminated with signal 9

**Comment by Ublimjo** [comment]
downloading bootstrap package
decompressing bootstrap image image
Archive:  /data/data/com.termux/files/home/chrooted-termux/bootstrap.zip
   creating: share/
   creating: share/tabset/
  inflating: share/tabset/vt100      
  inflating: share/tabset/vt300      
  inflating: share/tabset/stdcrt     
  inflating: share/tabset/std        
   creating: share/terminfo/
   creating: share/terminfo/l/
  inflating: share/terminfo/l/linux  
   creating: share/terminfo/p/
  inflating: share/terminfo/p/putty-256color  
  inflating: share/terminfo/p/putty  
   creating: share/terminfo/e/
  inflating: share/terminfo/e/eterm-color  
   creating: share/terminfo/a/
  inflating: share/terminfo/a/ansi   
   creating: share/terminfo/s/
  inflating: share/terminfo/s/screen  
  inflating: share/terminfo/s/screen2  
  inflating: share/terminfo/s/screen-256color  
   creating: share/terminfo/t/
  inflating: share/terminfo/t/tmux   
  inflating: share/terminfo/t/tmux-256color  
   creating: share/terminfo/n/
  inflating: share/terminfo/n/nsterm  
   creating: share/terminfo/v/
  inflating: share/terminfo/v/vt100  
  inflating: share/terminfo/v/vt102  
  inflating: share/terminfo/v/vt52   
   creating: share/terminfo/d/
  inflating: share/terminfo/d/dtterm  
  inflating: share/terminfo/d/dumb   
   creating: share/terminfo/x/
  inflating: share/terminfo/x/xterm-256color  
  inflating: share/terminfo/x/xterm  
  inflating: share/terminfo/x/xterm-color  
  inflating: share/terminfo/x/xterm-new  
  inflating: share/terminfo/x/xterm-16color  
  inflating: share/terminfo/x/xterm+256color  
   creating: share/terminfo/r/
  inflating: share/terminfo/r/rxvt-unicode-256color  
  inflating: share/terminfo/r/rxvt-256color  
  inflating: share/terminfo/r/rxvt   
  inflating: share/terminfo/r/rxvt-unicode  
   creating: share/bash-completion/
   creating: share/bash-completion/completions/
  inflating: share/bash-completion/completions/apt  
   creating: share/man/
   creating: share/man/man1/
  inflating: share/man/man1/dpkg.1   
  inflating: share/man/man1/dpkg-genbuildinfo.1  
  inflating: share/man/man1/gpgv.1   
  inflating: share/man/man1/busybox.1  
  inflating: share/man/man1/dash.1   
  inflating: share/man/man1/dpkg-query.1  
  inflating: share/man/man1/dpkg-split.1  
  inflating: share/man/man1/dpkg-divert.1  
  inflating: share/man/man1/dpkg-deb.1  
  inflating: share/man/man1/bash.1   
  inflating: share/man/man1/dpkg-trigger.1  
   creating: share/man/man7/
  inflating: share/man/man7/deb-version.7  
   creating: bin/
  inflating: bin/termux-wake-lock    
  inflating: bin/getprop             
  inflating: bin/dpkg-divert         
  inflating: bin/dpkg                
  inflating: bin/apt-config          
  inflating: bin/dpkg-split          
  inflating: bin/ip                  
  inflating: bin/dpkg-genbuildinfo   
  inflating: bin/dpkg-trigger        
  inflating: bin/pkg                 
  inflating: bin/apt                 
  inflating: bin/ping6               
  inflating: bin/termux-fix-shebang  
  inflating: bin/settings            
  inflating: bin/termux-reload-settings  
  inflating: bin/apt-key             
  inflating: bin/logcat              
  inflating: bin/termux-wake-unlock  
  inflating: bin/dpkg-query          
  inflating: bin/am                  
  inflating: bin/apt-get             
  inflating: bin/bash                
  inflating: bin/chsh                
  inflating: bin/busybox             
  inflating: bin/dalvikvm            
  inflating: bin/apt-cache           
  inflating: bin/apt-mark            
  inflating: bin/termux-setup-storage  
  inflating: bin/dash                
  inflating: bin/dpkg-deb            
  inflating: bin/df                  
  inflating: bin/termux-open-url     
   creating: bin/applets/
  inflating: bin/gpgv                
  inflating: bin/pm                  
  inflating: bin/login               
  inflating: bin/termux-info         
  inflating: bin/su                  
  inflating: bin/termux-open         
  inflating: bin/ping                
   creating: lib/
  inflating: lib/libapt-private.so   
  inflating: lib/libreadline.so.7.0  
  inflating: lib/libnghttp2.so       
  inflating: lib/libhistory.so.7.0   
  inflating: lib/libcrypto.so.1.0.0  
  inflating: lib/libtermux-exec.so   
  inflating: lib/libapt-pkg.so       
   creating: lib/apt/
   creating: lib/apt/methods/
  inflating: lib/apt/methods/http    
  inflating: lib/apt/methods/file    
  inflating: lib/apt/methods/store   
  inflating: lib/apt/methods/copy    
  inflating: lib/apt/methods/https   
  inflating: lib/apt/methods/rsh     
  inflating: lib/apt/methods/gpgv    
  inflating: lib/libandroid-support.so  
   creating: lib/bash/
  inflating: lib/bash/setpgid        
  inflating: lib/bash/id             
  inflating: lib/bash/truefalse      
  inflating: lib/bash/tee            
  inflating: lib/bash/basename       
  inflating: lib/bash/logname        
  inflating: lib/bash/Makefile.inc   
  inflating: lib/bash/sync           
  inflating: lib/bash/printenv       
  inflating: lib/bash/pathchk        
  inflating: lib/bash/finfo          
  inflating: lib/bash/mkdir          
  inflating: lib/bash/print          
  inflating: lib/bash/whoami         
  inflating: lib/bash/ln             
  inflating: lib/bash/uname          
  inflating: lib/bash/push           
  inflating: lib/bash/mypid          
  inflating: lib/bash/tty            
  inflating: lib/bash/sleep          
  inflating: lib/bash/unlink         
  inflating: lib/bash/realpath       
  inflating: lib/bash/dirname        
  inflating: lib/bash/strftime       
  inflating: lib/bash/rmdir          
  inflating: lib/bash/head           
  inflating: lib/libssl.so.1.0.0     
  inflating: lib/libncursesw.so.6.1  
  inflating: lib/liblzma.so          
  inflating: lib/libc++_shared.so    
  inflating: lib/libcurl.so          
   creating: var/
   creating: var/lib/
   creating: var/lib/dpkg/
   creating: var/lib/dpkg/triggers/
 extracting: var/lib/dpkg/available  
   creating: var/lib/dpkg/info/
  inflating: var/lib/dpkg/info/apt.md5sums  
  inflating: var/lib/dpkg/info/liblzma.md5sums  
  inflating: var/lib/dpkg/info/ncurses.list  
  inflating: var/lib/dpkg/info/readline.md5sums  
  inflating: var/lib/dpkg/info/ca-certificates.list  
  inflating: var/lib/dpkg/info/ncurses.md5sums  
  inflating: var/lib/dpkg/info/libandroid-support.md5sums  
  inflating: var/lib/dpkg/info/command-not-found.md5sums  
  inflating: var/lib/dpkg/info/termux-tools.md5sums  
  inflating: var/lib/dpkg/info/liblzma.list  
  inflating: var/lib/dpkg/info/termux-am.md5sums  
  inflating: var/lib/dpkg/info/dash.md5sums  
  inflating: var/lib/dpkg/info/libcurl.list  
  inflating: var/lib/dpkg/info/busybox.list  
  inflating: var/lib/dpkg/info/dpkg.list  
  inflating: var/lib/dpkg/info/gpgv.md5sums  
  inflating: var/lib/dpkg/info/libcurl.md5sums  
  inflating: var/lib/dpkg/info/libnghttp2.md5sums  
  inflating: var/lib/dpkg/info/dpkg.md5sums  
  inflating: var/lib/dpkg/info/apt.list  
  inflating: var/lib/dpkg/info/openssl.md5sums  
  inflating: var/lib/dpkg/info/dash.list  
  inflating: var/lib/dpkg/info/termux-exec.md5sums  
  inflating: var/lib/dpkg/info/readline.list  
  inflating: var/lib/dpkg/info/ca-certificates.md5sums  
  inflating: var/lib/dpkg/info/termux-exec.list  
  inflating: var/lib/dpkg/info/openssl.list  
  inflating: var/lib/dpkg/info/libc++.list  
  inflating: var/lib/dpkg/info/command-not-found.list  
  inflating: var/lib/dpkg/info/termux-tools.list  
  inflating: var/lib/dpkg/info/termux-am.list  
  inflating: var/lib/dpkg/info/busybox.md5sums  
  inflating: var/lib/dpkg/info/bash.md5sums  
  inflating: var/lib/dpkg/info/gpgv.list  
  inflating: var/lib/dpkg/info/libc++.md5sums  
  inflating: var/lib/dpkg/info/libnghttp2.list  
  inflating: var/lib/dpkg/info/bash.list  
  inflating: var/lib/dpkg/info/libandroid-support.list  
   creating: var/lib/dpkg/updates/
  inflating: var/lib/dpkg/status     
   creating: var/lib/apt/
   creating: var/lib/apt/lists/
   creating: var/lib/apt/lists/partial/
   creating: var/log/
   creating: var/log/apt/
   creating: var/cache/
   creating: var/cache/apt/
   creating: var/cache/apt/archives/
   creating: var/cache/apt/archives/partial/
   creating: var/spool/
   creating: var/spool/cron/
   creating: var/spool/cron/crontabs/
  inflating: var/spool/cron/crontabs/README.termux  
   creating: var/service/
   creating: var/service/telnetd/
  inflating: var/service/telnetd/run  
   creating: var/service/ftpd/
  inflating: var/service/ftpd/run    
   creating: etc/
   creating: etc/apt/
 extracting: etc/apt/trusted.gpg     
   creating: etc/apt/preferences.d/
   creating: etc/apt/apt.conf.d/
  inflating: etc/apt/sources.list    
  inflating: etc/profile             
  inflating: etc/bash.bashrc         
  inflating: etc/inputrc             
   creating: etc/tls/
   creating: etc/tls/misc/
  inflating: etc/tls/misc/CA.sh      
  inflating: etc/tls/misc/CA.pl      
  inflating: etc/tls/misc/c_hash     
  inflating: etc/tls/misc/tsget      
  inflating: etc/tls/misc/c_issuer   
  inflating: etc/tls/misc/c_info     
  inflating: etc/tls/misc/c_name     
  inflating: etc/tls/openssl.cnf     
  inflating: etc/tls/cert.pem        
  inflating: etc/motd                
   creating: tmp/
  inflating: SYMLINKS.txt            
   creating: libexec/
   creating: libexec/termux/
  inflating: libexec/termux/command-not-found  
   creating: libexec/termux-am/
  inflating: libexec/termux-am/am.apk  
creating symlink for libhistory.so.7.0←lib/libhistory.so.7
creating symlink for libreadline.so.7.0←lib/libreadline.so.7
creating symlink for libhistory.so.7.0←lib/libhistory.so
creating symlink for libreadline.so.7.0←lib/libreadline.so
creating symlink for libncursesw.so.6.1←lib/libncursesw.so.6
creating symlink for libncursesw.so.6.1←lib/libncurses.so.6.1
creating symlink for libncursesw.so.6.1←lib/libncurses.so
creating symlink for libncursesw.so.6.1←lib/libncursesw.so
creating symlink for ../share/terminfo←lib/terminfo
creating symlink for libncursesw.so.6.1←lib/libncurses.so.6
creating symlink for termux-open←bin/xdg-open
creating symlink for dash.1←share/man/man1/sh.1
creating symlink for dash←bin/sh
creating symlink for libandroid-support.so←lib/libiconv.so
creating symlink for busybox←bin/env
creating symlink for ../busybox←bin/applets/makemime
creating symlink for ../busybox←bin/applets/touch
creating symlink for ../busybox←bin/applets/nc
creating symlink for ../busybox←bin/applets/unlzma
creating symlink for ../busybox←bin/applets/chown
creating symlink for ../busybox←bin/applets/mv
creating symlink for ../busybox←bin/applets/cmp
creating symlink for ../busybox←bin/applets/pstree
creating symlink for ../busybox←bin/applets/bunzip2
creating symlink for ../busybox←bin/applets/diff
creating symlink for ../busybox←bin/applets/comm
creating symlink for ../busybox←bin/applets/pscan
creating symlink for ../busybox←bin/applets/id
creating symlink for ../busybox←bin/applets/expr
creating symlink for ../busybox←bin/applets/more
creating symlink for ../busybox←bin/applets/cp
creating symlink for ../busybox←bin/applets/gunzip
creating symlink for ../busybox←bin/applets/uncompress
creating symlink for ../busybox←bin/applets/rev
creating symlink for ../busybox←bin/applets/pidof
creating symlink for ../busybox←bin/applets/unexpand
creating symlink for ../busybox←bin/applets/tee
creating symlink for ../busybox←bin/applets/smemcap
creating symlink for ../busybox←bin/applets/mpstat
creating symlink for ../busybox←bin/applets/crontab
creating symlink for ../busybox←bin/applets/fuser
creating symlink for ../busybox←bin/applets/route
creating symlink for ../busybox←bin/applets/mknod
creating symlink for ../busybox←bin/applets/basename
creating symlink for ../busybox←bin/applets/top
creating symlink for ../busybox←bin/applets/bzip2
creating symlink for ../busybox←bin/applets/grep
creating symlink for ../busybox←bin/applets/chgrp
creating symlink for ../busybox←bin/applets/uniq
creating symlink for ../busybox←bin/applets/sed
creating symlink for ../busybox←bin/applets/uptime
creating symlink for ../busybox←bin/applets/time
creating symlink for ../busybox←bin/applets/timeout
creating symlink for ../busybox←bin/applets/ttysize
creating symlink for ../busybox←bin/applets/od
creating symlink for ../busybox←bin/applets/vi
creating symlink for ../busybox←bin/applets/lsusb
creating symlink for ../busybox←bin/applets/svlogd
creating symlink for ../busybox←bin/applets/sum
creating symlink for ../busybox←bin/applets/false
creating symlink for ../busybox←bin/applets/shuf
creating symlink for ../busybox←bin/applets/ps
creating symlink for ../busybox←bin/applets/lzma
creating symlink for ../busybox←bin/applets/less
creating symlink for ../busybox←bin/applets/cut
creating symlink for ../busybox←bin/applets/usleep
creating symlink for ../busybox←bin/applets/uudecode
creating symlink for ../busybox←bin/applets/yes
creating symlink for ../busybox←bin/applets/dos2unix
creating symlink for ../busybox←bin/applets/sync
creating symlink for ../busybox←bin/applets/iostat
creating symlink for ../busybox←bin/applets/unzip
creating symlink for ../busybox←bin/applets/ifconfig
creating symlink for ../busybox←bin/applets/watch
creating symlink for ../busybox←bin/applets/split
creating symlink for ../busybox←bin/applets/awk
creating symlink for ../busybox←bin/applets/udpsvd
creating symlink for ../busybox←bin/applets/kill
creating symlink for ../busybox←bin/applets/printenv
creating symlink for ../busybox←bin/applets/sha256sum
creating symlink for ../busybox←bin/applets/script
creating symlink for ../busybox←bin/applets/lsof
creating symlink for ../busybox←bin/applets/runsvdir
creating symlink for ../busybox←bin/applets/clear
creating symlink for ../busybox←bin/applets/pipe_progress
creating symlink for ../busybox←bin/applets/runsv
creating symlink for ../busybox←bin/applets/xz
creating symlink for ../busybox←bin/applets/chrt
creating symlink for ../busybox←bin/applets/mktemp
creating symlink for ../busybox←bin/applets/ipcalc
creating symlink for ../busybox←bin/applets/chattr
creating symlink for ../busybox←bin/applets/tcpsvd
creating symlink for ../busybox←bin/applets/linux64
creating symlink for ../busybox←bin/applets/mkdir
creating symlink for ../busybox←bin/applets/hostname
creating symlink for ../busybox←bin/applets/nmeter
creating symlink for ../busybox←bin/applets/gzip
creating symlink for ../busybox←bin/applets/lsattr
creating symlink for ../busybox←bin/applets/seq
creating symlink for ../busybox←bin/applets/sv
creating symlink for ../busybox←bin/applets/whoami
creating symlink for ../busybox←bin/applets/dc
creating symlink for ../busybox←bin/applets/base64
creating symlink for ../busybox←bin/applets/fold
creating symlink for ../busybox←bin/applets/nohup
creating symlink for ../busybox←bin/applets/strings
creating symlink for ../busybox←bin/applets/linux32
creating symlink for ../busybox←bin/applets/crond
creating symlink for ../busybox←bin/applets/dd
creating symlink for ../busybox←bin/applets/rx
creating symlink for ../busybox←bin/applets/cal
creating symlink for ../busybox←bin/applets/wget
creating symlink for ../busybox←bin/applets/ln
creating symlink for ../busybox←bin/applets/printf
creating symlink for ../busybox←bin/applets/nice
creating symlink for ../busybox←bin/applets/inotifyd
creating symlink for ../busybox←bin/applets/uname
creating symlink for ../busybox←bin/applets/ftpget
creating symlink for ../busybox←bin/applets/env
creating symlink for ../busybox←bin/applets/reset
creating symlink for ../busybox←bin/applets/date
creating symlink for ../busybox←bin/applets/find
creating symlink for ../busybox←bin/applets/cat
creating symlink for ../busybox←bin/applets/whois
creating symlink for ../busybox←bin/applets/httpd
creating symlink for ../busybox←bin/applets/readlink
creating symlink for ../busybox←bin/applets/chpst
creating symlink for ../busybox←bin/applets/setsid
creating symlink for ../busybox←bin/applets/renice
creating symlink for ../busybox←bin/applets/tr
creating symlink for ../busybox←bin/applets/pgrep
creating symlink for ../busybox←bin/applets/tftp
creating symlink for ../busybox←bin/applets/popmaildir
creating symlink for ../busybox←bin/applets/stty
creating symlink for ../busybox←bin/applets/ftpput
creating symlink for ../busybox←bin/applets/fsync
creating symlink for ../busybox←bin/applets/tar
creating symlink for ../busybox←bin/applets/sort
creating symlink for ../busybox←bin/applets/tty
creating symlink for ../busybox←bin/applets/unxz
creating symlink for ../busybox←bin/applets/start-stop-daemon
creating symlink for ../busybox←bin/applets/sha512sum
creating symlink for ../busybox←bin/applets/chmod
creating symlink for ../busybox←bin/applets/sleep
creating symlink for ../busybox←bin/applets/which
creating symlink for ../busybox←bin/applets/true
creating symlink for ../busybox←bin/applets/unlink
creating symlink for ../busybox←bin/applets/wc
creating symlink for ../busybox←bin/applets/arp
creating symlink for ../busybox←bin/applets/sysctl
creating symlink for ../busybox←bin/applets/killall
creating symlink for ../busybox←bin/applets/hexdump
creating symlink for ../busybox←bin/applets/patch
creating symlink for ../busybox←bin/applets/pmap
creating symlink for ../busybox←bin/applets/ar
creating symlink for ../busybox←bin/applets/free
creating symlink for ../busybox←bin/applets/xargs
creating symlink for ../busybox←bin/applets/realpath
creating symlink for ../busybox←bin/applets/softlimit
creating symlink for ../busybox←bin/applets/pwd
creating symlink for ../busybox←bin/applets/tac
creating symlink for ../busybox←bin/applets/pwdx
creating symlink for ../busybox←bin/applets/rm
creating symlink for ../busybox←bin/applets/tftpd
creating symlink for ../busybox←bin/applets/telnet
creating symlink for ../busybox←bin/applets/pkill
creating symlink for ../busybox←bin/applets/run-parts
creating symlink for ../busybox←bin/applets/setuidgid
creating symlink for ../busybox←bin/applets/du
creating symlink for ../busybox←bin/applets/dirname
creating symlink for ../busybox←bin/applets/hd
creating symlink for ../busybox←bin/applets/tail
creating symlink for ../busybox←bin/applets/getopt
creating symlink for ../busybox←bin/applets/test
creating symlink for ../busybox←bin/applets/rmdir
creating symlink for ../busybox←bin/applets/sha1sum
creating symlink for ../busybox←bin/applets/resize
creating symlink for ../busybox←bin/applets/uuencode
creating symlink for ../busybox←bin/applets/bbconfig
creating symlink for ../busybox←bin/applets/md5sum
creating symlink for ../busybox←bin/applets/scriptreplay
creating symlink for ../busybox←bin/applets/sha3sum
creating symlink for ../busybox←bin/applets/telnetd
creating symlink for ../busybox←bin/applets/cksum
creating symlink for ../busybox←bin/applets/egrep
creating symlink for ../busybox←bin/applets/expand
creating symlink for ../busybox←bin/applets/head
creating symlink for ../busybox←bin/applets/nproc
creating symlink for ../busybox←bin/applets/cpio
creating symlink for ../busybox←bin/applets/install
creating symlink for ../busybox←bin/applets/netstat
creating symlink for ../busybox←bin/applets/reformime
creating symlink for ../busybox←bin/applets/echo
creating symlink for ../busybox←bin/applets/unix2dos
creating symlink for ../busybox←bin/applets/ls
creating symlink for ../busybox←bin/applets/mkfifo
creating symlink for ../busybox←bin/applets/envdir
creating symlink for ../busybox←bin/applets/sendmail
creating symlink for ../busybox←bin/applets/ftpd
creating symlink for libssl.so.1.0.0←lib/libssl.so
creating symlink for libcrypto.so.1.0.0←lib/libcrypto.so
creating symlink for store←lib/apt/methods/lzma
creating symlink for store←lib/apt/methods/xz
creating symlink for rsh←lib/apt/methods/ssh
creating symlink for store←lib/apt/methods/gzip
making files in bin executable
making files in libexec executable
making files in lib/apt/methods executable
Setting permissions of root directory
writing launch script
fixing shebang of start.sh
making start.sh executable

**Comment by Neo-Oli** [comment]
What device do you have?

This is perhaps related to https://github.com/termux/termux-packages/issues/258

**Comment by Ublimjo** [comment]
Asus P01Z
i686

**Comment by Neo-Oli** [comment]
I don't think there is anything I can do on the side of this script to fix this.

**Comment by ghost** [comment]
Did you upgrade packages?
